import yfinance as yf
import pandas as pd
import os
import requests
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

# --- FORENSIC ALPHA UNIVERSE (735 STOCKS) ---
STOCKS = [
   "360ONE.NS", "3IINFOLTD.NS", "3MINDIA.NS", "5PAISA.NS", "AARTIDRUGS.NS", "AARTIIND.NS", "AARTIPHARM.NS", "AAVAS.NS", 
    "ABB.NS", "ABBOTINDIA.NS", "ABCAPITAL.NS", "ABFRL.NS", "ACC.NS", "ACCELYA.NS", "ACI.NS", "ADANIENSOL.NS", 
    "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADVENZYMES.NS", "AEQUS.NS", "AFFLE.NS", "AGARIND.NS", "AGI.NS", 
    "AHLUCONT.NS", "AIAENG.NS", "AJANTPHARM.NS", "AKZOINDIA.NS", "ALEMBICLTD.NS", "ALICON.NS", "ALKEM.NS", "ALKYLAMINE.NS", 
    "AMBER.NS", "AMBIKCO.NS", "AMBUJACEM.NS", "ANANDRATHI.NS", "ANDHRAPAP.NS", "ANDHRSUGAR.NS", "ANGELONE.NS", "APCOTEXIND.NS", 
    "APEX.NS", "APLAPOLLO.NS", "APLLTD.NS", "APOLLOHOSP.NS", "APOLLOPIPE.NS", "APOLLOTYRE.NS", "APTUS.NS", "ARTEMISMED.NS", 
    "ARVIND.NS", "ARVINDFASN.NS", "ASAHIINDIA.NS", "ASHIANA.NS", "ASHOKA.NS", "ASHOKLEY.NS", "ASIANPAINT.NS", "ASTERDM.NS", 
    "ASTRAL.NS", "ASTRAMICRO.NS", "ASTRAZEN.NS", "ATGL.NS", "ATUL.NS", "AUBANK.NS", "AUROPHARMA.NS", "AUTOAXLES.NS", 
    "AVADHSUGAR.NS", "AVANTIFEED.NS", "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJAJCON.NS", "BAJAJELEC.NS", "BAJAJFINSV.NS", "BAJAJHLDNG.NS", 
    "BAJFINANCE.NS", "BALAMINES.NS", "BALKRISIND.NS", "BALMLAWRIE.NS", "BALRAMCHIN.NS", "BANCOINDIA.NS", "BANDHANBNK.NS", "BANKBARODA.NS", 
    "BANKINDIA.NS", "BANSWRAS.NS", "BASF.NS", "BATAINDIA.NS", "BAYERCROP.NS", "BBTC.NS", "BDL.NS", "BECTORFOOD.NS", 
    "BEL.NS", "BEML.NS", "BEPL.NS", "BERGEPAINT.NS", "BFINVEST.NS", "BHARATFORG.NS", "BHARATRAS.NS", "BHARTIARTL.NS", 
    "BHEL.NS", "BIL.NS", "BIOCON.NS", "BIRLACORPN.NS", "BLS.NS", "BLUEDART.NS", "BLUESTARCO.NS", "BODALCHEM.NS", 
    "BOSCHLTD.NS", "BPCL.NS", "BRIGADE.NS", "BRITANNIA.NS", "BSE.NS", "BSOFT.NS", "CAMPUS.NS", "CAMS.NS", 
    "CANBK.NS", "CANFINHOME.NS", "CANHLIFE.NS", "CAPACITE.NS", "CAPLIPOINT.NS", "CARBORUNIV.NS", "CARERATING.NS", "CARYSIL.NS", 
    "CASTROLIND.NS", "CCL.NS", "CDSL.NS", "CEATLTD.NS", "CENTENKA.NS", "CENTRALBK.NS", "CENTURYPLY.NS", "CERA.NS", 
    "CESC.NS", "CGCL.NS", "CGPOWER.NS", "CHAMBLFERT.NS", "CHEMPLASTS.NS", "CHENNPETRO.NS", "CHOLAHLDNG.NS", "CHOLAFIN.NS", 
    "CIEINDIA.NS", "CIPLA.NS", "CLEAN.NS", "COALINDIA.NS", "COCHINSHIP.NS", "COFORGE.NS", "COLPAL.NS", "CONCOR.NS", 
    "CONCORDBIO.NS", "COROMANDEL.NS", "CRAFTSMAN.NS", "CREDITACC.NS", "CRISIL.NS", "CROMPTON.NS", "CSBBANK.NS", "CUB.NS", 
    "CUMMINSIND.NS", "CYIENT.NS", "DABUR.NS", "DALBHARAT.NS", "DATAPATTNS.NS", "DCAL.NS", "DCBBANK.NS", "DCMSHRIRAM.NS", 
    "DCW.NS", "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS", "DELTACORP.NS", "DEN.NS", "DENORA.NS", "DEVYANI.NS", 
    "DGCONTENT.NS", "DHAMPURSUG.NS", "DHANI.NS", "DHARMAJ.NS", "DIAMONDYD.NS", "DICIND.NS", "DISHTV.NS", "DIVISLAB.NS", 
    "DIXON.NS", "DLF.NS", "DMART.NS", "DOLLAR.NS", "DONEAR.NS", "DPABHUSHAN.NS", "DPSCLTD.NS", "DREAMFOLKS.NS", 
    "DREDGECORP.NS", "DRREDDY.NS", "DSSL.NS", "DTL.NS", "DUCON.NS", "DVL.NS", "DWARKESH.NS", "DYCL.NS", 
    "DYNAMATECH.NS", "EASEMYTRIP.NS", "EBBETF.NS", "ECLERX.NS", "EDELWEISS.NS", "EICHERMOT.NS", "EIDPARRY.NS", "EIHOTEL.NS", 
    "ELECON.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "EMUDHRA.NS", "ENDURANCE.NS", "ENGINERSIN.NS", "ENIL.NS", "EPL.NS", 
    "EQUITASBNK.NS", "ERIS.NS", "ESCORTS.NS", "ETHOSLTD.NS", "EUREKAFORB.NS", "EVERESTIND.NS", "EXIDEIND.NS", "FCL.NS", 
    "FDC.NS", "FEDERALBNK.NS", "FIEMIND.NS", "FILATEX.NS", "FINCABLES.NS", "FINEORG.NS", "FINPIPE.NS", "FLUOROCHEM.NS", 
    "FMGOETZE.NS", "FORTIS.NS", "FSL.NS", "GABRIEL.NS", "GAIL.NS", "GALAXYSURF.NS", "GANESHHOUC.NS", "GANRS.NS", 
    "GARFIBRES.NS", "GATEWAY.NS", "GEECEE.NS", "GENESYS.NS", "GENSOL.NS", "GENUSPOWER.NS", "GEOJITFSL.NS", "GEPIL.NS", 
    "GESHIP.NS", "GHCL.NS", "GICRE.NS", "GILLANDERS.NS", "GILLETTE.NS", "GINNIFILA.NS", "GLAND.NS", "GLAXO.NS", 
    "GLENMARK.NS", "GLS.NS", "GMDCLTD.NS", "GMMPFAUDLR.NS", "GMRINFRA.NS", "GNFC.NS", "GOCOLORS.NS", "GODREJAGRO.NS", 
    "GODREJCP.NS", "GODREJIND.NS", "GODREJPROP.NS", "GPIL.NS", "GPPL.NS", "GRANULES.NS", "GRAPHITE.NS", "GRASIM.NS", 
    "GRAVITA.NS", "GREAVESCOT.NS", "GRINFRA.NS", "GRINDWELL.NS", "GRSE.NS", "GSFC.NS", "GSLSU.NS", "GSPL.NS", 
    "GUJGASLTD.NS", "GUJRAFFIA.NS", "GULFOILLUB.NS", "GULPOLY.NS", "HAL.NS", "HAPPSTMNDS.NS", "HARSHA.NS", "HATHWAY.NS", 
    "HATSUN.NS", "HAVELLS.NS", "HBLPOWER.NS", "HCLTECH.NS", "HDFCAMC.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HEG.NS", 
    "HERANBA.NS", "HEROMOTOCO.NS", "HESTERBIO.NS", "HFCL.NS", "HIKAL.NS", "HIL.NS", "HIMATSEIDE.NS", "HINDALCO.NS", 
    "HINDCOMPOS.NS", "HINDCOPPER.NS", "HINDONIL.NS", "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS", "HIRECT.NS", "HISARMET.NS", 
    "HITECH.NS", "HITECHGEAR.NS", "HLVTD.NS", "HMT.NS", "HMVL.NS", "HNDFDS.NS", "HOMEFIRST.NS", "HONAUT.NS", 
    "HONDAPOWER.NS", "HOVS.NS", "HPAL.NS", "HPL.NS", "HSCL.NS", "HTMEDIA.NS", "HUBTOWN.NS", "HUDCO.NS", 
    "HUHTAMAKI.NS", "HYBRIDANON.NS", "ICICIBANK.NS", "ICICIGI.NS", "ICICIPRULI.NS", "ICRA.NS", "IDBI.NS", "IDEA.NS", 
    "IDFC.NS", "IDFCFIRSTB.NS", "IEX.NS", "IFBIND.NS", "IFCI.NS", "IGL.NS", "IGPL.NS", "IIFL.NS", 
    "IIFLSEC.NS", "IITL.NS", "IMAGICAA.NS", "IMFA.NS", "INDHOTEL.NS", "INDIACEM.NS", "INDIAGLYCO.NS", "INDIAMART.NS", 
    "INDIANB.NS", "INDIANHUME.NS", "INDIGO.NS", "INDIGOPNTS.NS", "INDNIPPON.NS", "INDOCO.NS", "INDORAMA.NS", "INDOSTAR.NS", 
    "INDOTECH.NS", "INDOTHAI.NS", "INDOWIND.NS", "INDUSINDBK.NS", "INDUSTOWER.NS", "INEOSSTYRO.NS", "INFIBEAM.NS", "INFY.NS", 
    "INGERRAND.NS", "INOXGREEN.NS", "INOXINDIA.NS", "INOXWIND.NS", "INTELLECT.NS", "INTLCONV.NS", "IOB.NS", "IOC.NS", 
    "IOLCP.NS", "IPCALAB.NS", "IPLADVISOR.NS", "IRB.NS", "IRCON.NS", "IRCTC.NS", "IRFC.NS", "IRISDOREME.NS", 
    "ISGEC.NS", "ISMTLTD.NS", "ITC.NS", "ITDC.NS", "ITDCEM.NS", "ITI.NS", "IVC.NS", "IVP.NS", 
    "IXIGO.NS", "IZMO.NS", "J&KBANK.NS", "JAGRAN.NS", "JAIBALAJI.NS", "JAICORPLTD.NS", "JAKHARIA.NS", "JAMNAAUTO.NS", 
    "JASH.NS", "JAYAGROGN.NS", "JAYBARMARU.NS", "JAYNECOIND.NS", "JAYSREETEA.NS", "JBCHEPHARM.NS", "JBMAUTO.NS", "JCHAC.NS", 
    "JETAIRWAYS.NS", "JINDALPHOT.NS", "JINDALPOLY.NS", "JINDALSAW.NS", "JINDALSTEL.NS", "JINDWORLD.NS", "JIOFIN.NS", "JISLJALEQS.NS", 
    "JKCEMENT.NS", "JKIL.NS", "JKLAKSHMI.NS", "JKPAPER.NS", "JKTYRE.NS", "JMA.NS", "JMFINANCIL.NS", "JOCIL.NS", 
    "JPASSOCIAT.NS", "JPPOWER.NS", "JSL.NS", "JSWENERGY.NS", "JSWHL.NS", "JSWINFRA.NS", "JSWSTEEL.NS", "JTEKTINDIA.NS", 
    "JTLIND.NS", "JUBLFOOD.NS", "JUBLINGREA.NS", "JUBLPHARMA.NS", "JUSTDIAL.NS", "JYOTHYLAB.NS", "JYOTICNC.NS", "KABRAEXTRU.NS", 
    "KAJARIACER.NS", "KALAMANDIR.NS", "KALPATPOWR.NS", "KALYANKJIL.NS", "KANSAINER.NS", "KARURVYSYA.NS", "KAVVERITEL.NS", "KAYA.NS", 
    "KAYNES.NS", "KCP.NS", "KCPSUGIND.NS", "KEC.NS", "KEI.NS", "KELLTONTEC.NS", "KENNAMET.NS", "KESORAMIND.NS", 
    "KEYCORP.NS", "KFINTECH.NS", "KHADIM.NS", "KICL.NS", "KILITCH.NS", "KIMS.NS", "KINETICENG.NS", "KIRLFER.NS", 
    "KIRLOSBROS.NS", "KIRLOSENG.NS", "KIRLOSIND.NS", "KITEX.NS", "KNRCON.NS", "KOHINOOR.NS", "KOKUYOCMLN.NS", "KOLTEPATIL.NS", 
    "KOPRAN.NS", "KOTAKBANK.NS", "KOTARISUG.NS", "KOTHARIPRO.NS", "KPIGREEN.NS", "KPIL.NS", "KPITTECH.NS", "KPRMILL.NS", 
    "KRBL.NS", "KRIDHANINF.NS", "KRISHANA.NS", "KRSNAA.NS", "KSL.NS", "KSCL.NS", "KSHITIJPOL.NS", "KSL.NS", 
    "KSUMAR.NS", "KTKBANK.NS", "KUANTUM.NS", "L&TFH.NS", "LALPATHLAB.NS", "LAMBODHARA.NS", "LAOPALA.NS", "LASA.NS", 
    "LAURUSLABS.NS", "LAXMICOT.NS", "LEMONTREE.NS", "LEXUS.NS", "LEYAH.NS", "LGBBROSLTD.NS", "LIBAS.NS", "LIBERTSHOE.NS", 
    "LICHSGFIN.NS", "LICI.NS", "LIKHITHA.NS", "LINCOLN.NS", "LINDEINDIA.NS", "LLOYDSME.NS", "LODHA.NS", "LOKESHMACH.NS", 
    "LOTUSCHO.NS", "LOVABLE.NS", "LOYALTV.NS", "LTIM.NS", "LT.NS", "LTTS.NS", "LUMAXIND.NS", "LUMAXTECH.NS", 
    "LUPIN.NS", "LUXIND.NS", "LXCHEM.NS", "LYKALABS.NS", "LYPSAGEMS.NS", "M&MFIN.NS", "M&M.NS", "MAANALU.NS", 
    "MACPOWER.NS", "MADHAV.NS", "MADHUCON.NS", "MADRASFERT.NS", "MAGADSUGAR.NS", "MAGNUM.NS", "MAHABANK.NS", "MAHESHWARI.NS", 
    "MAHLIFE.NS", "MAHLOG.NS", "MAHSEAMLES.NS", "MAHSCOOTER.NS", "MAITHANALL.NS", "MAJESCO.NS", "MALUPAPER.NS", "MANALIPETC.NS", 
    "MANAPPURAM.NS", "MANGLMCEM.NS", "MANINDS.NS", "MANINFRA.NS", "MANORAMA.NS", "MANORG.NS", "MANUGRAPH.NS", "MARALOVER.NS", 
    "MARATHON.NS", "MARICO.NS", "MARINE.NS", "MARKSANS.NS", "MARUTI.NS", "MASFIN.NS", "MASKINVEST.NS", "MASTEK.NS", 
    "MATRIMONY.NS", "MAWANASUG.NS", "MAXHEALTH.NS", "MAZDA.NS", "MAZDOCK.NS", "MBAPL.NS", "MBECL.NS", "MBLINFRA.NS", 
    "MCDOWELL-N.NS", "MCL.NS", "MCX.NS", "MEDANTA.NS", "MEDICAMEQ.NS", "MEDPLUS.NS", "MEGASOFT.NS", "MELSTAR.NS", 
    "MENONBE.NS", "MEP.NS", "MERCATOR.NS", "METALFORGE.NS", "METROBRAND.NS", "METROPOLIS.NS", "MFSL.NS", "MGL.NS", 
    "MHRIL.NS", "MICEL.NS", "MIDHANI.NS", "MINDACORP.NS", "MINDTECK.NS", "MIRCELECTR.NS", "MIRZAINT.NS", "MITTAL.NS", 
    "MMFL.NS", "MMP.NS", "MMTC.NS", "MODIRUBBER.NS", "MODISNME.NS", "MOHITIND.NS", "MOIL.NS", "MOKSH.NS", 
    "MOL.NS", "MONTECARLO.NS", "MORARJEE.NS", "MOREPENLAB.NS", "MOTHERSON.NS", "MOTILALOFS.NS", "MOTOGENFIN.NS", "MPHASIS.NS", 
    "MPSLTD.NS", "MRF.NS", "MRO-TEK.NS", "MRPL.NS", "MSUMI.NS", "MTARTECH.NS", "MTNL.NS", "MUKANDLTD.NS", 
    "MUKTAARTS.NS", "MUNJALAU.NS", "MUNJALSHOW.NS", "MURUDCERA.NS", "MUTHOOTCAP.NS", "MUTHOOTFIN.NS", "NACLIND.NS", "NAGAFERT.NS", 
    "NAGREEKEXP.NS", "NAHARCAP.NS", "NAHARINDUS.NS", "NAHARPOLY.NS", "NAHARSPING.NS", "NAM-INDIA.NS", "NARMADA.NS", "NATCOPHARM.NS", 
    "NATIONALUM.NS", "NAUKRI.NS", "NAVA.NS", "NAVINFLUOR.NS", "NAVKARCORP.NS", "NAVNETEDUL.NS", "NAZARA.NS", "NBCC.NS", 
    "NBIFIN.NS", "NCC.NS", "NCLIND.NS", "NDL.NS", "NDRAUTO.NS", "NDTV.NS", "NECCLTD.NS", "NEELAM.NS", 
    "NEELKANTH.NS", "NEGEN.NS", "NELCAST.NS", "NELCO.NS", "NEOGEN.NS", "NESCO.NS", "NESTLEIND.NS", "NETWORK18.NS", 
    "NEULANDLAB.NS", "NEWGEN.NS", "NEXTMEDIA.NS", "NFL.NS", "NGIL.NS", "NGLFINE.NS", "NH.NS", "NHPC.NS", 
    "NIACL.NS", "NIBL.NS", "NIITLTD.NS", "NILAINFRA.NS", "NILASPACES.NS", "NILKAMAL.NS", "NIMBUS.NS", "NIPPO.NS", 
    "NIRAJ.NS", "NITCO.NS", "NITINSPIN.NS", "NITIRAJ.NS", "NKIND.NS", "NLCINDIA.NS", "NMDC.NS", "NOCIL.NS", 
    "NOIDATOLL.NS", "NORBTEAEXP.NS", "NORTHARC.NS", "NRAIL.NS", "NRBBEARING.NS", "NSIL.NS", "NTPC.NS", "NUCLEUS.NS", 
    "NURECA.NS", "NYKAA.NS", "OAL.NS", "OBEROIRLTY.NS", "OCCL.NS", "OFSS.NS", "OIL.NS", "OLECTRA.NS", 
    "OMAXAUTO.NS", "OMAXE.NS", "OMINFRAL.NS", "ONELIFECAP.NS", "ONGC.NS", "ONMOBILE.NS", "ONWARDTEC.NS", "OPTIEMUS.NS", 
    "ORBTEXP.NS", "ORCHPHARMA.NS", "ORICONENT.NS", "ORIENTALTL.NS", "ORIENTBELL.NS", "ORIENTCEM.NS", "ORIENTELEC.NS", "ORIENTHOT.NS", 
    "ORIENTLTD.NS", "ORIENTPPR.NS", "ORISSAMINE.NS", "ORTINLAB.NS", "OSWALAGRO.NS", "PAGEIND.NS", "PAISALO.NS", "PALASHSEPY.NS", 
    "PANACEABIO.NS", "PANAMY.NS", "PANORAMA.NS", "PARACABLES.NS", "PARAGMILK.NS", "PARAS.NS", "PARSVNATH.NS", "PASUPATI.NS", 
    "PATANJALI.NS", "PATELENG.NS", "PATINTLOG.NS", "PAYTM.NS", "PCBL.NS", "PCJEWELLER.NS", "PDMJUSTICE.NS", "PDS.NS", 
    "PEARLPOLY.NS", "PEL.NS", "PENIND.NS", "PENINLAND.NS", "PERSISTENT.NS", "PETRONET.NS", "PFC.NS", "PFIZER.NS", 
    "PGEL.NS", "PGHH.NS", "PGHL.NS", "PHCAPITAL.NS", "PHILIPCARB.NS", "PHOENIXLTD.NS", "PIDILITIND.NS", "PIGL.NS", 
    "PIIND.NS", "PILANIINVS.NS", "PILITA.NS", "PNCINFRA.NS", "PNB.NS", "PNBHOUSING.NS", "PNC.NS", "POCHIRAJU.NS", 
    "PODDARHOUS.NS", "PODDARMENT.NS", "POKARNA.NS", "POLYCAB.NS", "POLYMED.NS", "POLYPLEX.NS", "PONNIERODE.NS", "POONAWALLA.NS", 
    "POWERGRID.NS", "POWERMECH.NS", "PPAP.NS", "PPLPHARMA.NS", "PRADIP.NS", "PRAJIND.NS", "PRAKASH.NS", "PRAKASHSTL.NS", 
    "PRAXIS.NS", "PRECAM.NS", "PRECOT.NS", "PRECWIRE.NS", "PREMEXPLN.NS", "PREMIER.NS", "PREMIERPOL.NS", "PRESSMN.NS", 
    "PRESTIGE.NS", "PRICOLLTD.NS", "PRIMESECU.NS", "PRINCEPIPE.NS", "PRSMJOHNSN.NS", "PRUDENT.NS", "PSB.NS", "PSPPROJECT.NS", 
    "PTC.NS", "PTL.NS", "PUNJABCHEM.NS", "PURVA.NS", "PVRINOX.NS", "QUESS.NS", "QUICKHEAL.NS", "RADAAN.NS", 
    "RADICO.NS", "RADIOCITY.NS", "RAILTEL.NS", "RAIN.NS", "RAINBOW.NS", "RAJESHEXPO.NS", "RAJMET.NS", "RAJRATAN.NS", 
    "RAJSREESUG.NS", "RAJTV.NS", "RALLIS.NS", "RAMANEWS.NS", "RAMASTEEL.NS", "RAMCOCEM.NS", "RAMCOIND.NS", "RAMCOSYS.NS", 
    "RAMKY.NS", "RANASUG.NS", "RANEENGINE.NS", "RANEHOLDIN.NS", "RATNAMANI.NS", "RAYMOND.NS", "RBLBANK.NS", "RBL.NS", 
    "RCF.NS", "RECLTD.NS", "REDINGTON.NS", "REFEX.NS", "RELAXO.NS", "RELIANCE.NS", "RELIGARE.NS", "RELINFRA.NS", 
    "REMSONSIND.NS", "RENUKA.NS", "REPCOHOME.NS", "REPL.NS", "REPRO.NS", "RESPONIND.NS", "REVATHI.NS", "RGL.NS", 
    "RHFL.NS", "RICOAUTO.NS", "RIIL.NS", "RITES.NS", "RKFORGE.NS", "RML.NS", "ROHLTD.NS", "ROLEXTECHS.NS", 
    "ROTO.NS", "ROUTE.NS", "RPGLIFE.NS", "RPOWER.NS", "RPPINFRA.NS", "RPSGVENT.NS", "RSSOFTWARE.NS", "RSWM.NS", 
    "RSYSTEMS.NS", "RTNINDIA.NS", "RTNPOWER.NS", "RUBYMILLS.NS", "RUCHIRA.NS", "RUPA.NS", "RUSTOMJEE.NS", "RVNL.NS", 
    "S&SPOWER.NS", "SABEVENTS.NS", "SADBHAV.NS", "SADBHIN.NS", "SAFARI.NS", "SAGCEM.NS", "SAIL.NS", "SAKSOFT.NS", 
    "SAKUMA.NS", "SALASAR.NS", "SALONA.NS", "SALSTEEL.NS", "SALZERELEC.NS", "SAMBHAAV.NS", "SAMMAANCAP.NS", "SAMHI.NS", 
    "SAMKRG.NS", "SAMVARDHANA.NS", "SANCO.NS", "SANDHAR.NS", "SANDUMA.NS", "SANGAMIND.NS", "SANGHIIND.NS", "SANGHVIMOV.NS", 
    "SANGINITA.NS", "SANOFI.NS", "SANSERA.NS", "SAPPHIRE.NS", "SARDAEN.NS", "SAREGAIA.NS", "SARLAPOLY.NS", "SASKEN.NS", 
    "SASTASUNDR.NS", "SATIA.NS", "SATIN.NS", "SAYAJIHOTL.NS", "SBICARD.NS", "SBILIFE.NS", "SBIN.NS", "SCAPDVR.NS", 
    "SCHAEFFLER.NS", "SCHNEIDER.NS", "SCI.NS", "SCILAL.NS", "SDBL.NS", "SEAMECLTD.NS", "SECURCRED.NS", "SEQUENT.NS", 
    "SESHAPAPER.NS", "SETCO.NS", "SETUINFRA.NS", "SFL.NS", "SGFL.NS", "SGL.NS", "SHAFALIMET.NS", "SHAHALLOYS.NS", 
    "SHAKTIPUMP.NS", "SHALBY.NS", "SHALPAINTS.NS", "SHANKARA.NS", "SHANTIGEAR.NS", "SHARDACROP.NS", "SHARDAMOTR.NS", "SHAREINDIA.NS", 
    "SHEMAROO.NS", "SHILPAMED.NS", "SHIVALIK.NS", "SHMARN.NS", "SHOPERSTOP.NS", "SHRADHA.NS", "SHREDIGCEM.NS", "SHREECEM.NS", 
    "SHREEPUSHK.NS", "SHREERAMA.NS", "SHRENIK.NS", "SHREYANSCP.NS", "SHREYAS.NS", "SHRIPIPES.NS", "SHRIRAMFIN.NS", "SHRIRAMPPS.NS", 
    "SHUKRA.NS", "SHYAMMETL.NS", "SHYAMTEL.NS", "SICAGEN.NS", "SICAL.NS", "SIEMENS.NS", "SIGACHI.NS", "SIGMA.NS", 
    "SIKKO.NS", "SIL.NS", "SILINV.NS", "SILLYMONKS.NS", "SILLYMONKS.NS", "SIMBHAOLI.NS", "SIMMONDS.NS", "SIMPLEXINF.NS", 
    "SINTERCOM.NS", "SIRCA.NS", "SIS.NS", "SITINET.NS", "SIYSIL.NS", "SJS.NS", "SKFINDIA.NS", "SKMEGGPROD.NS", 
    "SKIPPER.NS", "SKP.NS", "SLARETER.NS", "SMCGLOBAL.NS", "SMLISUZU.NS", "SMLT.NS", "SMSLIFE.NS", "SMSPHARMA.NS", 
    "SNOWMAN.NS", "SOBHA.NS", "SOFTTECH.NS", "SOLARA.NS", "SOLARINDS.NS", "SOMANYCERE.NS", "SOMATEX.NS", "SOMICONVEY.NS", 
    "SONACOMS.NS", "SONAMCLOCK.NS", "SONATSOFTW.NS", "SOTL.NS", "SOUTHBANK.NS", "SOUTHWEST.NS", "SPAL.NS", "SPANDANA.NS", 
    "SPARC.NS", "SPECIALITY.NS", "SPENCERS.NS", "SPIC.NS", "SPLPETRO.NS", "SPMLINFRA.NS", "SPORTKING.NS", "SREELTD.NS", 
    "SREINFRA.NS", "SRF.NS", "SRHHL.NS", "SRIADITYA.NS", "SRPL.NS", "SSWL.NS", "STAR.NS", "STARCEMENT.NS", 
    "STARHEALTH.NS", "STARPAPER.NS", "STCINDIA.NS", "STEELCAS.NS", "STEELCITY.NS", "STEELXIND.NS", "STEL.NS", "STERTOOLS.NS", 
    "STLTECH.NS", "STOVEKRAFT.NS", "STYLAMIND.NS", "SUBCAPCITY.NS", "SUBEXLTD.NS", "SUBROS.NS", "SUDARSCHEM.NS", "SUMICHEM.NS", 
    "SUMIT.NS", "SUMMITSEC.NS", "SUNCLAYLTD.NS", "SUNDARAM.NS", "SUNDARMFIN.NS", "SUNDRMFAST.NS", "SUNFLAG.NS", "SUNPHARMA.NS", 
    "SUNTECK.NS", "SUNTV.NS", "SUPERHOUSE.NS", "SUPERSPIN.NS", "SUPRAJIT.NS", "SUPREMEIND.NS", "SUPREMEINF.NS", "SUPREMESUR.NS", 
    "SURAJEST.NS", "SURAJLTD.NS", "SURYALAXMI.NS", "SURYAROSNI.NS", "SURYODAY.NS", "SUTLEJTEX.NS", "SUULD.NS", "SUVEN.NS", 
    "SUVENPHAR.NS", "SUZLON.NS", "SVLL.NS", "SVPGLOB.NS", "SWANENERGY.NS", "SWARAJENG.NS", "SWELECTES.NS", "SWSOLAR.NS", 
    "SYMPHONY.NS", "SYNGENE.NS", "SYRMA.NS", "TAINWALCHM.NS", "TAJGVK.NS", "TAKE.NS", "TALBROAUTO.NS", "TANLA.NS", 
    "TANTIACONS.NS", "TARMAT.NS", "TARSONS.NS", "TASTYBITE.NS", "TATACHEM.NS", "TATACOMM.NS", "TATACONSUM.NS", "TATAELXSI.NS", 
    "TATAINVEST.NS", "TATAMETALI.NS", "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TATATECH.NS", "TAV.NS", "TCI.NS", 
    "TCIEXP.NS", "TCNSBRANDS.NS", "TCPLPACK.NS", "TCS.NS", "TDPOWEREG.NS", "TEAMLEASE.NS", "TECHM.NS", "TECHNOE.NS", 
    "TEGA.NS", "TEJASNET.NS", "TEMBO.NS", "TERASOFT.NS", "TEXINFRA.NS", "TEXRAIL.NS", "TFCILTD.NS", "TFL.NS", 
    "TGBHOTELS.NS", "THANGAMAYL.NS", "THEINVEST.NS", "THEMISMED.NS", "THERMAX.NS", "THOMASCOOK.NS", "THOMASCOTT.NS", "THYROCARE.NS", 
    "TI.NS", "TIDW.NS", "TIIL.NS", "TIINDIA.NS", "TIJARIA.NS", "TIL.NS", "TIMESGTY.NS", "TIMETECHNO.NS", 
    "TIMKEN.NS", "TIPSMUSIC.NS", "TIRUMALCHM.NS", "TITAGARH.NS", "TITAN.NS", "TMB.NS", "TNPETRO.NS", "TNPL.NS", 
    "TNTELE.NS", "TOKYOPLAST.NS", "TOLINS.NS", "TORNTPHARM.NS", "TORNTPOWER.NS", "TRENT.NS", "TRIDENT.NS", "TRITURBINE.NS", 
    "TRIVENI.NS", "TVSMOTOR.NS", "UBL.NS", "UFLEX.NS", "UJJIVANSFB.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UNITDSPR.NS", 
    "UNOMINDA.NS", "UPL.NS", "USHAMART.NS", "UTIAMC.NS", "VAIBHAVGBL.NS", "VARROC.NS", "VBL.NS", "VEDL.NS", 
    "VGUARD.NS", "VIDYAWIRES.NS", "VIJAYA.NS", "VIKRAN.NS", "VINATIORGA.NS", "VIPIND.NS", "VMART.NS", "VOLTAMP.NS", 
    "VOLTAS.NS", "VRLLOG.NS", "VTL.NS", "WABAG.NS", "WELCORP.NS", "WELSPUNLIV.NS", "WESTLIFE.NS", "WIPRO.NS", 
    "WONDERLA.NS", "WSTCSTPAPR.NS", "YATRA.NS", "YESBANK.NS", "ZENSARTECH.NS", "ZFCVINDIA.NS", "ZOTA.NS", "ZYDUSLIFE.NS", 
    "ZYDUSWELL.NS"
]

# Get Credentials from GitHub Secrets
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

def send_telegram_msg(message):
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        print("Telegram credentials missing.")
        return
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {"chat_id": TELEGRAM_CHAT_ID, "text": message, "parse_mode": "HTML"}
    try:
        requests.post(url, json=payload)
    except Exception as e:
        print(f"Error sending telegram: {e}")

def scan_stock(ticker):
    """Fetches data and checks for forensic anomalies."""
    try:
        # Fetching 5 days of data to compare current vs average
        df = yf.download(ticker, period="5d", interval="1d", progress=False)
        if df.empty or len(df) < 2:
            return None
        
        last_close = df['Close'].iloc[-1].item()
        prev_close = df['Close'].iloc[-2].item()
        last_vol = df['Volume'].iloc[-1].item()
        avg_vol = df['Volume'].iloc[:-1].mean().item()
        
        price_change = ((last_close - prev_close) / prev_close) * 100
        vol_spike = last_vol / avg_vol if avg_vol > 0 else 0
        
        # ANOMALY LOGIC: 5% price move OR 3x Volume spike (Forensic Audit Triggers)
        if abs(price_change) >= 5.0 or vol_spike >= 3.0:
            return {
                "ticker": ticker,
                "price": round(last_close, 2),
                "change": round(price_change, 2),
                "vol_ratio": round(vol_spike, 2)
            }
    except:
        return None
    return None

def main():
    start_time = time.time()
    print(f"Starting Forensic Audit for {len(STOCKS)} stocks...")
    
    anomalies = []
    
    # PROCESS IN PARALLEL: 10 threads effectively manage the 735-stock load
    with ThreadPoolExecutor(max_workers=10) as executor:
        future_to_stock = {executor.submit(scan_stock, stock): stock for stock in STOCKS}
        
        for i, future in enumerate(as_completed(future_to_stock)):
            result = future.result()
            if result:
                anomalies.append(result)
            
            # HEARTBEAT: Keeps GitHub Action alive by printing progress
            if (i + 1) % 50 == 0:
                print(f"Progress: {i+1}/{len(STOCKS)} scanned... Elapsed: {time.time() - start_time:.2f}s")

    # Final Alerting
    if anomalies:
        msg = "<b>🚨 Forensic Alpha Alert: Anomalies Detected</b>\n\n"
        for a in anomalies:
            direction = "📈" if a['change'] > 0 else "📉"
            msg += f"{direction} <b>{a['ticker']}</b>: ₹{a['price']} ({a['change']}%) | Vol: {a['vol_ratio']}x\n"
        send_telegram_msg(msg)
    
    print(f"Scan complete in {time.time() - start_time:.2f} seconds.")

if __name__ == "__main__":
    main()
